# Generated by Django 6.1.1 on 2026-10-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0005_hall_created_at_hall_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='description',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='features',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='image',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='hall',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='URL slug'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='area',
            field=models.PositiveIntegerField(default=0, verbose_name='Площадь (м²)'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='capacity_banquet',
            field=models.PositiveIntegerField(default=0, verbose_name='Вместимость (банкет)'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='capacity_buffet',
            field=models.PositiveIntegerField(default=0, verbose_name='Вместимость (фуршет)'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='line_color',
            field=models.CharField(default='#000000', max_length=20, verbose_name='Цвет линии'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='line_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='Номер линии'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название зала'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='price_from',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена от'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
    ]
