# Generated by Django 6.1.1 on 2026-10-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0006_remove_hall_created_at_remove_hall_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='slug',
            field=models.SlugField(default=1, unique=True, verbose_name='URL slug'),
            preserve_default=False,
        ),
    ]
