# Generated by Django 6.1.1 on 2026-10-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0008_hall_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='description',
            field=models.TextField(blank=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='hall',
            name='features',
            field=models.TextField(blank=True, verbose_name='Особенности'),
        ),
        migrations.AddField(
            model_name='hall',
            name='image',
            field=models.CharField(blank=True, max_length=255, verbose_name='Путь к картинке (например, img/hall-depo.jpg)'),
        ),
    ]
