# Generated by Django 6.1.1 on 2026-10-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0009_hall_description_hall_features_hall_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='URL slug'),
        ),
    ]
